/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.dicoding.kotlin

import com.dicoding.kotlin.functionalprogramming.slice
import com.dicoding.kotlin.whenexpression.WhenExpression
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val value: Int? = null
        println(value.slice)
    }
}
